### ISSUE TITLE
Error check needlessly makes monochrome pngquant images fail

### ISSUE THREAD

**Issue by ghost** [gagern/jspngopt#2]
Parser.js lines 39 40
```
  // if ((hdr.colorType & 2) !== 0 && hdr.bitDepth < 8)
  //   throw Error("Multi-sample sub-byte images are disallowed");
```

Make example image:
1. Draw with black paintbrush in pinta with transparent background.
2. Reduce to monochrome
`pngquant 2 foo.png`

I just hacked it to make it work (node 7.2.1)
`if ((hdr.colorType & 2) !== 0 && hdr.bitDepth < 8 && !(hdr.colorType===3 && hdr.bitDepth===1))`

**Comment by gagern** [comment]
This is as per [the PNG specification](http://www.libpng.org/pub/png/spec/1.2/PNG-DataRep.html#DR.Image-layout):

> PNG permits multi-sample pixels only with 8- and 16-bit samples, so multiple samples of a single pixel are never packed into one byte.

So I'd say that if your file really fails this check, it is in violation of the PNG specification. On the other hand, the spec offers an alternative solution:

> In an indexed-color image, an alpha value can be defined for each palette entry.

So you can take your black-on-transparent image as a one-bit (two colors) indexed image, without violating the specification.

I'm closing this now. If you think there are reasons to re-open, feel free to comment and I'll consider.

**Comment by ghost** [comment]
Interesting, what is a multi-sample pixel?

Well yes, I expect my image must be an indexed colour image. I just made one recently that's 280x100 pixels, scribbled a capital A inside it, and after `pngquant 2` it was 439 bytes. That's too small for each pixel to have contained a separate byte.

I think you must be missing something because
1. `pngquant 2 foo.png` produces these images that the above check says is illegal.
2. If I bypass that check code, the image is made smaller, and it works in browsers and pinta.
3. optipng processes the `pngquant 2 foo.png` image without any complaints and produces an output image the same size as point 2.

Perhaps try running `pngquant 2 foo.png` to test for yourself?

**Comment by gagern** [comment]
A multi-sample pixel is one which has multiple sample values associated with each pixel. Often also referred to as multiple channels. You have 4 samples per pixel for red+green+blue+alpha translucent true color images, 3 samples for red+green+blue opaque true-color, 2 samples for index+alpha  or gray+alpha or 1 sample for a sole index or gray value.

Looking at [the table of color types](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.IHDR) I see that I mistook bit 2 as representing multiple samples: the indexed+alpha approach isn't even an option with PNG. And color type 3, which is what we have here, comes with a single sample per pixel.

    [0, 3].indexOf(hdr.colorType) === -1 && bitDepth < 8

would be the more appropriate condition. Will include this in the next release. Thanks!

**Comment by ghost** [comment]
Thanks, glad we've resolved this :) :+1:
